name: Profile Autofix
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    name: Autofix profile content
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          ref:  ${{ github.head_ref }}
      - name: Autofix profile
        id: autofix-profile
        uses: RedHatProductSecurity/trestle-bot@main
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          branch: ${{ github.head_ref }}
          file_pattern: "*.json,markdown/*"
          skip_items: "fedramp_rev5_high"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}