name: Profile Autofix
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    name: Autofix profile content
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Generate app token
        uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"contents": "write"}
      - name: Autofix profile
        id: autofix-profile
        uses: RedHatProductSecurity/trestle-bot@main
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          branch: ${{ inputs.branch }}
          file_pattern: "*.json,markdown/*"
          skip_items: "fedramp_rev5_high"
        env:
          GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token }}