name: Dispatch downstreams

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [Regenerate profile content]
    types:
      - completed

jobs:
  dispatch:
    name: Dispatch to Downstreams
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"actions": "write"}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'RedHatProductSecurity',
              repo: 'oscal-component-definitions',
              workflow_id: 'update-profiles.yml',
              ref: 'main'
            })
        