name: Dispatch downstreams

on:
  release:
    types: [published]

jobs:
  dispatch:
    name: Dispatch to Downstreams
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2.1.0
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"actions": "write"}
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'RedHatProductSecurity',
              repo: 'oscal-component-definitions',
              workflow_id: 'update-profiles.yml',
              inputs: {
                ref: '${{ github.event.release.tag_name }}'
              },
              ref: 'main'
            })
        