name: Evaluate profiles
on:
  pull_request:
    types: [ opened, review_requested, ready_for_review, reopened, synchronize ]
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'
jobs:
  test:
    name: Evaluate profiles
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          ref:  ${{ github.head_ref }}
      - name: Check profile
        id: check-profile
        uses: RedHatProductSecurity/trestle-bot@main
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          check_only: true
          skip_items: "fedramp_rev5_high"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  call-autofix:
    needs: [test]
    permissions:
      contents: write
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/autofix-profile.yml