name: Evaluate profiles

on:
  pull_request:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Evaluate profiles
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Check profile
        id: check
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@v0.10.1
        with:
          markdown_path: "markdown/profiles"
          oscal_model: "profile"
          skip_items: "fedramp_rev5_high"
          dry_run: true
      - name: Fail
        if: ${{ steps.check.outputs.changes == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('Changes detected. Manual intervention may be required.')
    
  call-autosync:
    needs: [test]
    if: |
      always() && contains(needs.*.result, 'failure')
      && github.event.pull_request.base.repo.url == github.event.pull_request.head.repo.url
    uses: ./.github/workflows/autosync-profile.yml
    with:
      branch: ${{ github.head_ref }}
    secrets: inherit